name: npm-publish
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Automatic GitHub Release
        id: release
        uses: justincy/github-action-npm-release@2.0.2
      - name: Setup node
        if: ${{ steps.release.outputs.released == 'true' }}
        uses: actions/setup-node@v5.0.0
        with:
          registry-url: https://registry.npmjs.org/
      - name: Publish to npm
        if: ${{ steps.release.outputs.released == 'true' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
