name: npm-publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  release:
    needs: build
    outputs:
      contiune: ${{ steps.set_output.outputs.contiune }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Automatic GitHub Release
        id: release
        uses: justincy/github-action-npm-release@2.0.1
      - name: Set output
        id: set_output
        env:
          RESULT: ${{ steps.release.outputs.released }}
        run: |
          if [[ $RESULT == true]] then
            echo "::set-output name=continue::true"
          else
            echo "::set-output name=contiune::false"
          fi

  publish-npm:
    needs: release
    if: needs.release.outputs.continue == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}